### ISSUE TITLE
Had this fatal crash with secret rooms a couple of times

### ISSUE THREAD

**Issue by Mr-Syntax** [bl4ckscor3/CeilingTorch#40]
[14:35:45] [Worker-Main6/ERROR]: Exception caught during firing event: TORCH_LEVER
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class bl4ckscor3.mod.ceilingtorch.CeilingTorchClient onInterModProcess(Lnet/minecraftforge/fml/event/lifecycle/InterModProcessEvent;)V
java.lang.NoSuchFieldError: TORCH_LEVER
	at bl4ckscor3.mod.ceilingtorch.compat.secretrooms.SecretRoomsCompat.getPlaceEntries(SecretRoomsCompat.java:29)
	at bl4ckscor3.mod.ceilingtorch.CeilingTorchClient.onInterModProcess(CeilingTorchClient.java:20)
	at net.minecraftforge.eventbus.ASMEventHandler_984_CeilingTorchClient_onInterModProcess_InterModProcessEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2626/2123721485.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at net.minecraftforge.fml.ModContainer$$Lambda$3537/1988464942.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[14:35:45] [Worker-Main3/INFO]: Starting[3] SP...
[14:35:45] [Worker-Main6/ERROR]: Caught exception during event InterModProcessEvent dispatch for modid ceilingtorch
java.lang.NoSuchFieldError: TORCH_LEVER
	at bl4ckscor3.mod.ceilingtorch.compat.secretrooms.SecretRoomsCompat.getPlaceEntries(SecretRoomsCompat.java:29) ~[?:v1.12]
	at bl4ckscor3.mod.ceilingtorch.CeilingTorchClient.onInterModProcess(CeilingTorchClient.java:20) ~[?:v1.12]
	at net.minecraftforge.eventbus.ASMEventHandler_984_CeilingTorchClient_onInterModProcess_InterModProcessEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2626/2123721485.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [?:36.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3537/1988464942.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[14:35:45] [Worker-Main3/INFO]: Got IMC []
[14:35:45] [modloading-worker-5/FATAL]: Failed to complete lifecycle event PROCESS_IMC, 1 errors found

**Comment by bl4ckscor3** [comment]
Which versions of Minecraft, Ceiling Torch, and Secret Rooms are you using?

**Comment by bl4ckscor3** [comment]
Ok I looked into it, and there is no apparent reason why that crash should happen. I rebuilt and reuploaded v1.13, and it should work now. https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/3378443

Next time when reporting a crash, please include the complete report which also contains version information, which is useful in trying to fix the error.
