### ISSUE TITLE
Crash with latest Malum update 1.18.2

### ISSUE THREAD

**Issue by Raidobw2** [bl4ckscor3/CeilingTorch#61]
Ceiling torch will crash with the new Malum and Ortus Lib update for 1.18.2.
Ortus Lib was renamed to Lodestone Lib, the package name may have changed?

MC 1.18.2, Forge 40.1.73
Ortus Lib => `lodestone-1.18.2-1.1.jar` => https://www.curseforge.com/minecraft/mc-mods/lodestonelib
`malum-1.18.2-1.4.jar`

```
	Caused by 1: java.lang.NoClassDefFoundError: com/sammy/ortus/systems/block/OrtusBlockProperties
		at bl4ckscor3.mod.ceilingtorch.CeilingTorch.<init>(CeilingTorch.java:71) ~[ceilingtorch-1.18.2-1.18.jar%2386!/:1.18] {re:classloading,pl:epic_rei_lmao:B}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.73.jar%23287!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.73.jar%23286!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:B}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:B}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

Thanks in advance

**Comment by Raidobw2** [comment]
Thank you for the fix, have a good weekend!
